from typing import Literal

# recos
SPLINEMPE = "splinempe"
MILLIPEDE = "millipede"

# catalogs
TURIN = "turin"
MILLIQUAS = "milliquas"

# statistical test
ALLOWED_CATALOGS = [TURIN, MILLIQUAS]
ALLOWED_RECONSTRUCTIONS = [SPLINEMPE, MILLIPEDE]
TURIN_INDEX = 0
SPLINEMPE_INDEX = 0
MILLIPEDE_INDEX = 1
DEFAULT_CATALOG = ALLOWED_CATALOGS[TURIN_INDEX]
DEFAULT_RECO = ALLOWED_RECONSTRUCTIONS[SPLINEMPE_INDEX]
ICECAT_FILENAME = "IceCube_Gold_Bronze_Tracks.csv"
ICECAT_DEC_NAME = "DEC"
ICECAT_ENERGY_NAME = "ENERGY"
EFFECTIVE_AREA_FILENAME = "Effa_all_streams_gold_bronze.txt"
EFFECTIVE_AREA_ENERGY_BINS_INDEX = 0
EFFECTIVE_AREA_30_90_DEG_INDEX = 1
EFFECTIVE_AREA_0_30_DEG_INDEX = 2
EFFECTIVE_AREA_MIN5_0_DEG_INDEX = 3
EFFECTIVE_AREA_MIN30_MIN5_DEG_INDEX = 4
EFFECTIVE_AREA_MIN90_MIN30_DEG_INDEX = 5
EFFECTIVE_AREA_DEC_BINS = [-90, -30, -5, 0, 30, 90]
HUBBLE_CONSTANT = 73  # km s^-1 Mpc^-1
MPC_TO_KM = 3.086e19
SPEED_OF_LIGHT = 299792458  # m s^-1
MJD_04102023 = 60132
MJD_GOLDBRONZE_START = 58635
MJD_ICECAT_START = 55695
DAYS_IN_YEAR = 365
SECONDS_IN_YEAR = DAYS_IN_YEAR * 24 * 60 * 60
FLUX_NU = 1e36  # s-1 GeV-1 at 100 GeV
CONSTANT_XRAY = 1e-4  # GeV-2
E0 = 100  # GeV
ATMO_GAMMA = 3.0
SPLINEMPE_FILENAME = "gcn_notices_gold_bronze.txt"
# IC190819A: Updated GCN Notice never reported
# IC191231A: in GCN Circular reported the day after
# IC200227A: Updated GCN Notice never reported
# IC210503A: Never reconstructed with SplineMPE because detector
# was in a test run configuration. Missing in SplineMPE catalog
# IC210510A: Updated GCN Notice never reported
# IC211117A: Updated GCN Notice never reported
# IC221223A: Updated GCN Notice never reported
# IC230120A: Updated GCN Notice never reported
SPLINEMPE_EXCEPTIONS = [
    "IC191231A",
    "IC190819A",
    "IC200227A",
    "IC210510A",
    "IC211117A",
    "IC221223A",
    "IC230220A",
]
# IC200120A: likely background
# IC230823A: likely background
SPLINEMPE_BACKGROUND = ["IC200120A", "IC230823A"]
SPLINEMPE_GCN_START = "<tr align=left>\n"
SPLINEMPE_INDEX_START = 65
SPLINEMPE_COMMENT_START = "<!--\n"
MILLIPEDE_FILENAME = "IC_Alerts_Table_Energies.csv"
MILLIPEDE_IC_NAME = "IC_NAME"
MILLIPEDE_RA = "RA"
MILLIPEDE_RA_PLUS = "RA_ERR_P"
MILLIPEDE_RA_MINUS = "RA_ERR_M"
MILLIPEDE_DEC = "DEC"
MILLIPEDE_DEC_PLUS = "DEC_ERR_P"
MILLIPEDE_DEC_MINUS = "DEC_ERR_M"
MILLIPEDE_ENERGY = "E [GeV]"
ROUND_ANGLE = 360  # deg
TEST_STATISTIC_EMPTY_SCRAMBLE = -1000
ERG_TO_GEV = 624.151
TEST_STATISTIC_FILENAME = "test_statistic"
FLUX_CHOICES = ["False", "True"]
TRUE_INDEX = 1
FALSE_INDEX = 0
MAX_DIST_FROM_SOURCE = 4.

HYPO_CHOICES = ["Background", "Doublet", "Population", "Doublet-inj", "Singlet-inj"]
DEC_JITTER_DEFAULT = None
BACKGROUND_INDEX = 0
DOUBLET_INDEX = 1
POPULATION_INDEX = 2
DOUBLET_INJ_INDEX = 3
SINGLET_INJ_INDEX = 4

# Flux plot
LINEWIDTH_FLUXPLOT = 3
FLUX1 = 1e36
FLUX2 = 1e39
FLUX3 = 1e34
FLUX4 = 1e42
DECS = 8.5

# plot sed
E_NU_2022 = 1.8399e05  # GeV
E_NU_2023 = 1.2729e05  # GeV
GEV_TO_ERG = 1.60218e-3
TEV_TO_ERG = 1e3 * GEV_TO_ERG
NUMBER_OF_NU = 2
SUPERIOR_ENERGY_BOUND = 2e7  # GeV
M2_TO_CM2 = 1e4
FLUX_NU_MIN_1068 = 2.9e-11 * 1.6  # erg*cm-2*s-1, at 1 TeV
FLUX_NU_MAX_1068 = 7.1e-11 * 1.6  # erg*cm-2*s-1, at 1 TeV
GAMMA_MIN_1068 = 3.0  # spectral index
GAMMA_MAX_1068 = 3.4  # spectral index
MIN_E_NU_1068 = 1.5e3  # GeV
MAX_E_NU_1068 = 1.5e4  # GeV
MAX_E_7YRS = 1e6  # TeV
MIN_E_7YRS = 1e-1  # TeV
LOG_WIDTH_7YRS_BINS = 0.5
INTRINSIC_HARD_XRAY_FLUX_1068 = 206.00e-12  # erg*cm-2*s-1
INTRINSIC_HARD_XRAY_FLUX_ERR_1068 = 22e-12
INTRINSIC_GAMMA_1068 = 2.37
INTRINSIC_GAMMA_ERR_1068 = 0.1
INTRINSIC_HARD_XRAY_FLUX_7469 = 64.30e-12  # erg*cm-2*s-1
INTRINSIC_HARD_XRAY_FLUX_ERR_7469 = 8e-12
INTRINSIC_GAMMA_7469 = 2.09
INTRINSIC_GAMMA_ERR_7469 = 0.12
ENERGY1_INTRINSIC_FLUX = 30  # keV
ENERGY2_INTRINSIC_FLUX = 70  # keV

# coincidence plots
RA_INDEX = 0
DE_INDEX = 1
PLUS_INDEX = 1
MINUS_INDEX = 0
CIRCULAR_23_COORDS = [345.85, 9.14]
CIRCULAR_23_ERRS = [[1.04, 0.90], [0.76, 0.81]]
CIRCULAR_22_COORDS = [346.11, 8.91]
CIRCULAR_22_ERRS = [[1.33, 1.26], [1.01, 0.95]]
NGC7469_COORDS = [345.8156, 8.873861]
CIRCULAR_PLOT_FILENAME = "GCNCirculars_ngc7469"
NOTICE_22_COORDS = [345.757, 8.856]
NOTICE_22_ERR = 0.66
NOTICE_23_COORDS = [345.825, 9.007]
NOTICE_23_ERR = 0.513
NOTICE_PLOT_FILENAME = "GCNNotices_ngc7469"
CIRCULAR_NOTICE_PLOT_FILENAME = "GCNCircularsNotices_ngc7469"

# plot test statistic
REDSHIFT = "redshift"
XRAY = "xray"
TS_FILENAME = "test_statistic"
FIGSIZE_TS = (5, 3.5)
NBINS_TS = 50
HISTTYPE_TS: Literal["bar", "barstacked", "step", "stepfilled"] = "step"
HISTTYPE_TS_ALT: Literal["bar", "barstacked", "step", "stepfilled"] = "stepfilled"
LINEWIDTH_TS = 2
TURIN_LABEL_TS = "Background distribution,\nTurin catalog"
MILLIQUAS_LABEL_TS = "Background distribution,\nMilliquas catalog"
AXVCOLOR_TS = "red"
AXVLINESTYLE_TS = "--"
AXVLABEL_TS = "IC220424A & IC230416A\nwith NGC 7469"
XLABEL_TS = "Negative test statistic"
YLABEL_TS = "N Datasets"
TITLE_TS = "Goodness of Fit test"
TITLE_UNBIASEDNESS = "Unbiasedness of the Goodness of Fit test"
XRAYTITLE_TS = "Goodness of Fit test, X-ray weighting"
MILLIPEDETITLE_TS = "Goodness of Fit test, Millipede"
MILLIPEDEXRAYTITLE_TS = "Goodness of Fit test, Millipede, X-ray weighting"
FONTSIZE_TS = "large"
AXISSCALE_TS = "log"
FIGNAME_TS = "TS_distr"
BBOX_INCHES = "tight"

# areas ratio
SPLINEMPE_MISSING = "IC210510A"
FIGSIZE_AREAS = (5, 4)
RANGE_BINS_AREAS = (-0.5, 3)
NBINS_AREAS = 10
ALPHA_AREAS = 0.8
HISTTYPE_AREAS: Literal["bar", "barstacked", "step", "stepfilled"] = "stepfilled"
LINEWIDTH_AREAS = 2
EDGECOLOR_AREAS = "darkblue"
LABEL_HIST_AREAS = r"$\dfrac{\mathrm{Millipede}}{\mathrm{SplineMPE}}$"
AVERAGE_COLOR_AREAS = "black"
AVERAGE_LINEWIDTH_AREAS = 3
AVERAGE_LINESTYLE_AREAS = "--"
LEGEND_FONTSIZE_AREAS = "x-large"
TICKS_FONTSIZE_AREAS = "x-large"
XLABEL_AREAS = "Ratio"
YLABEL_AREAS = "Counts"
AXIS_FONTSIZE_AREAS = "xx-large"
TITLE_AREAS = "Uncertainty areas"
TITLE_FONTSIZE_AREAS = "xx-large"
PLOTNAME_AREAS = "areas_ratio"
